version: "3"

services:
    www:
        build: ./
        container_name: shorturl_www
        restart: always
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html
        links:
            - db
    db:
        image: mysql
        container_name: shorturl_db
        restart: always
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        environment:
            MYSQL_DATABASE: shorturl
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456