version: "3"

services:
    www:
        build: ./
        ports: 
            - "80:80"
        volumes:
            - ./:/var/www/html
        links:
            - mariadb
    mariadb:
        image: mariadb:10.2.38
        command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci
        ports: 
            - "3306:3306"
        environment:
            MYSQL_DATABASE: shorturl
            MYSQL_USER: root
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: 123456

